ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  AUDIO:
    RIR_SAMPLING_RATE: 16000
  AGENT_0:
    SENSORS: ['DEPTH_SENSOR']

TASK:
  TYPE: AudioNav
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['SPECTROGRAM_SENSOR']
  GOAL_SENSOR_UUID: spectrogram

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION', 'SUCCESS', 'SPL', 'SOFT_SPL']
  SPL:
    TYPE: SPL
  GEOMETRIC_MAP:
    MAP_SIZE: 400
    INTERNAL_MAP_SIZE: 1200
    MAP_RESOLUTION: 0.1
  ACOUSTIC_MAP:
    MAP_SIZE: 20
    MAP_RESOLUTION: 1.0
  ACTION_MAP:
    MAP_SIZE: 9
    MAP_RESOLUTION: 1.0

DATASET:
  TYPE: "AudioNav"
  SPLIT: "val_mini"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/audionav/mp3d/{version}/{split}/{split}.json.gz"
